(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(backup-by-copying t)
 '(bar-cursor nil)
 '(blink-cursor-mode nil)
 '(column-number-mode t)
 '(global-linum-mode t)
 '(global-whitespace-mode t)
 '(kill-whole-line t)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount (quote (3 ((shift)) ((control) . 10))))
 '(scroll-bar-mode (quote right))
 '(show-paren-mode t)
 '(slime-kill-without-query-p t)
 '(tramp-default-user "lmeszaros")
 '(truncate-lines t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :background "#ffffff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "unknown" :family "FreeMono"))))
 '(bold ((t (:bold t))))
 '(bold-italic ((t (:bold t :italic t))))
 '(font-lock-builtin-face ((((class color) (background light)) (:foreground "Purple3"))))
 '(font-lock-comment-face ((((class color) (background light)) (:foreground "#88c"))))
 '(font-lock-constant-face ((t (:foreground "CadetBlue" :weight normal))))
 '(font-lock-function-name-face ((((class color) (background light)) (:foreground "brown4" :bold t))))
 '(font-lock-keyword-face ((((class color) (background light)) (:foreground "#a00"))))
 '(font-lock-preprocessor-face ((((class color) (background light)) (:foreground "#00a"))))
 '(font-lock-type-face ((((class color) (background light)) (:foreground "steelblue" :bold t))))
 '(font-lock-warning-face ((t (:foreground "#c00"))))
 '(linum ((t (:inherit (shadow default) :background "#f2f2f2" :foreground "darkgreen"))))
 '(paren-match ((t (:background "#d0ffff"))) t)
 '(secondary-selection ((t (:background "#ffffd0"))))
 '(show-paren-match ((((class color) (background light)) (:background "#d0ffff"))))
 '(sldb-catch-tag-face ((t (:foreground "yellow4"))))
 '(sldb-condition-face ((t (:bold t))))
 '(sldb-frame-label-face ((t (:foreground "#888"))))
 '(sldb-frame-line-face ((t nil)))
 '(sldb-restart-face ((t (:foreground "darkmagenta" :bold nil))))
 '(sldb-restart-number-face ((t (:foreground "darkmagenta" :bold t))))
 '(sldb-restart-type-face ((t (:foreground "darkmagenta" :bold nil))))
 '(sldb-section-face ((t (:foreground "darkblue" :bold t))))
 '(sldb-topline-face ((t (:foreground "darkred" :bold t))))
 '(slime-error-face ((((class color) (background light)) (:foreground "darkred" :bold t))))
 '(slime-inspector-value-face ((((background light)) (:foreground "MediumBlue" :bold t))))
 '(slime-note-face ((((class color) (background light)) (:background "grey80" :underline t))))
 '(slime-reader-conditional-face ((((background light)) (:foreground "DimGray" :bold t))))
 '(slime-repl-input-face ((t (:bold t))))
 '(slime-repl-output-mouseover-face ((t (:bold t))))
 '(slime-style-warning-face ((((class color) (background light)) (:underline t))))
 '(slime-warning-face ((((class color) (background light)) (:foreground "darkred" :underline t))))
 '(swbuff-current-buffer-face ((t (:foreground "red" :bold t :underline t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "#fff0f0"))))
 '(whitespace-trailing ((((class color) (background light)) (:background "#fff0f0")))))
(put 'narrow-to-region 'disabled nil)
