
;;
;; zu beachten:
;;
;; Pfadnamen VOLL ausgeschrieben, keine relativen Pfadnamen auf Unix, da sonst 
;; eventuell Probleme mit der File-Namen-Expansion unter einem Auto-Mounter 
;; oder unter z.B. afs auftauchen
;;
;; Außerdem müssen die Namen bei einer Kombination von NT/Unix/95 und Novell 
;; KLEIN geschrieben werden, da Windows95 nur durch Veränderung der Registry die 
;; Namens-Groß- und Kleinschreibung beibehält, was unter Unix zu Nichtauffindbarkeit
;; führt. Innerhalb der diary-Files müssen der Systemübersetzung halber die 
;; #include-Files mit Hilfe von Systemvariablen angegeben werden: Beispiel hier im
;; gleichen Verzeichnis unter dem File diary.
;;
(cond ((equal window-system 'x); Standard-Unix
       (setenv "GROUPDIARYDIR" "/amd/eiche/homes/netz/edv")
       (setq diary-file "/amd/eiche/homes/netz/??/diary")
       (setq personal-diary-file "/amd/eiche/homes/netz/edv/terminkalender_walther")
       (setq group-diary-file "/amd/eiche/homes/netz/edv/gruppenterminkalender")
       (setq information-file "/amd/eiche/homes/netz/edv/allgemeine_informationen"))
      ((equal system-type 'windows-nt)  ;; 95 und NT
       (setenv "GROUPDIARYDIR" "//eiche/edv")
       (setq diary-file "c:/programme/emacs/user/diary")
       (setq personal-diary-file "//eiche/edv/terminkalender_walther")
       (setq group-diary-file "//eiche/edv/gruppenterminkalender")
       (setq information-file "//eiche/edv/allgemeine_informationen"))
      ((not (or (equal system-type 'windows-nt)
		(equal window-system 'x))) ;; z.B. Ascii-Terminals -> hier gehen die auf Unix
       (setenv "GROUPDIARYDIR" "/amd/eiche/homes/netz/edv")
       (setq diary-file "/amd/eiche/homes/netz/??/diary")
       (setq personal-diary-file "/amd/eiche/homes/netz/edv/terminkalender_walther")
       (setq group-diary-file "/amd/eiche/homes/netz/edv/gruppenterminkalender")
       (setq information-file "/amd/eiche/homes/netz/edv/allgemeine_informationen")))

(setq signature "SMW")


(setq next-line-add-newlines nil)

(modify-syntax-entry ?0 "w")
(modify-syntax-entry ?1 "w")
(modify-syntax-entry ?2 "w")
(modify-syntax-entry ?3 "w")
(modify-syntax-entry ?4 "w")
(modify-syntax-entry ?5 "w")
(modify-syntax-entry ?6 "w")
(modify-syntax-entry ?7 "w")
(modify-syntax-entry ?8 "w")
(modify-syntax-entry ?9 "w")
(modify-syntax-entry ?\\ "w")
(modify-syntax-entry ?_ "w")
(modify-syntax-entry ?- "w")
(modify-syntax-entry ?$ "w")
(modify-syntax-entry ?ä "w")
(modify-syntax-entry ?Ä "w")
(modify-syntax-entry ?ö "w")
(modify-syntax-entry ?Ö "w")
(modify-syntax-entry ?ü "w")
(modify-syntax-entry ?Ü "w")
(modify-syntax-entry ?ß "w")


