(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(backup-by-copying t)
 '(bar-cursor nil)
 '(blink-cursor-mode nil)
 '(buffers-menu-format-buffer-line-function (quote slow-format-buffers-menu-line))
 '(column-number-mode t)
 '(complex-buffers-menu-p nil)
 '(delete-old-versions t)
 '(ecb-auto-activate t)
 '(ecb-options-version "2.31")
 '(ecb-primary-secondary-mouse-buttons (quote mouse-1--mouse-2))
 '(ecb-source-file-regexps (quote ((".*" ("\\(^\\(\\.\\|#\\)\\|\\(~$\\|\\.\\(fasl\\|fsl\\|elc\\|obj\\|o\\|class\\|lib\\|dll\\|a\\|so\\|cache\\)$\\)\\)") ("^\\.\\(emacs\\|gnus\\)$")))))
 '(ecb-source-path (quote ("~/workspace/dwim/" ("/" "/"))))
 '(ecb-tip-of-the-day nil)
 '(font-lock-maximum-size 500000)
 '(haskell-program-name "ghci")
 '(ido-auto-merge-delay-time 3.0)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(interprogram-cut-function nil t)
 '(interprogram-paste-function (quote x-cut-buffer-or-selection-value) t)
 '(kept-new-versions 5)
 '(kept-old-versions 5)
 '(kill-whole-line t)
 '(mouse-wheel-scroll-amount (quote (1 ((shift)) ((control) . 10))))
 '(paren-mode (quote sexp-surround) nil (paren))
 '(pc-selection-mode t nil (pc-select))
 '(permanent-buffers-alist nil)
 '(safe-local-variable-values (quote ((Syntax . COMMON-LISP) (Package . CL-USER) (Package . computed-class) (Syntax . ANSI-Common-Lisp) (Base . 10) (Syntax . Common-Lisp))))
 '(save-place-file "~/.emacs.d/places.el")
 '(scroll-bar-mode (quote right))
 '(show-paren-mode t)
 '(show-paren-style (quote expression))
 '(signal-error-on-buffer-boundary nil t)
 '(slime-kill-without-query-p t)
 '(slime-repl-history-size 3000)
 '(swbuff-clear-delay 3)
 '(swbuff-clear-delay-ends-switching t)
 '(swbuff-exclude-buffer-regexps (quote ("^ " "\\*.*\\*")))
 '(swbuff-separator " ### ")
 '(text-mode-hook (quote (turn-on-auto-fill text-mode-hook-identify)))
 '(tool-bar-mode nil)
 '(toolbar-visible-p nil)
 '(truncate-lines nil)
 '(undo-limit 3000000)
 '(undo-strong-limit 5000000)
 '(unshifted-motion-keys-deselect-region t t)
 '(version-control t)
 '(x-select-enable-clipboard t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :background "#ffffff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 127 :width normal :foundry "microsoft" :family "Consolas"))))
 '(bold ((t (:bold t))))
 '(bold-italic ((t (:bold t :italic t))))
 '(font-lock-builtin-face ((((class color) (background light)) (:foreground "Purple3"))))
 '(font-lock-comment-face ((((class color) (background light)) (:foreground "#88c"))))
 '(font-lock-constant-face ((t (:foreground "CadetBlue" :weight normal))))
 '(font-lock-function-name-face ((((class color) (background light)) (:foreground "brown4" :bold t))))
 '(font-lock-keyword-face ((((class color) (background light)) (:foreground "#a00"))))
 '(font-lock-preprocessor-face ((((class color) (background light)) (:foreground "#00a"))))
 '(font-lock-type-face ((((class color) (background light)) (:foreground "steelblue" :bold t))))
 '(font-lock-warning-face ((t (:foreground "Red3" :weight bold))))
 '(paren-match ((t (:background "#d0ffff"))) t)
 '(secondary-selection ((t (:background "#ffffd0"))))
 '(show-paren-match ((((class color) (background light)) (:background "#d0ffff"))))
 '(sldb-catch-tag-face ((t (:foreground "yellow4"))))
 '(sldb-condition-face ((t (:bold t))))
 '(sldb-frame-label-face ((t (:foreground "#888"))))
 '(sldb-frame-line-face ((t nil)))
 '(sldb-restart-face ((t (:foreground "darkmagenta" :bold nil))))
 '(sldb-restart-number-face ((t (:foreground "darkmagenta" :bold t))))
 '(sldb-restart-type-face ((t (:foreground "darkmagenta" :bold nil))))
 '(sldb-section-face ((t (:foreground "darkblue" :bold t))))
 '(sldb-topline-face ((t (:foreground "darkred" :bold t))))
 '(slime-error-face ((((class color) (background light)) (:foreground "darkred" :bold t))))
 '(slime-inspector-value-face ((((background light)) (:foreground "MediumBlue" :bold t))))
 '(slime-note-face ((((class color) (background light)) (:background "grey80" :underline t))))
 '(slime-reader-conditional-face ((((background light)) (:foreground "DimGray" :bold t))))
 '(slime-repl-input-face ((t (:bold t))))
 '(slime-repl-output-mouseover-face ((t (:bold t))))
 '(slime-style-warning-face ((((class color) (background light)) (:underline t))))
 '(slime-warning-face ((((class color) (background light)) (:foreground "darkred" :underline t))))
 '(swbuff-current-buffer-face ((t (:foreground "red" :bold t :underline t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "#fff0f0"))))
 '(whitespace-trailing ((((class color) (background light)) (:background "#fff0f0")))))
(put 'narrow-to-region 'disabled nil)
