#!/usr/bin/perl



sub my_copy
{
    local($file) = @_;
    system ("cp", 
	    "/homes/netz/walther/op-project/$file", 
	    "/homes/netz/walther/smbmounts/magnolie/Emacs/site-lisp/op-project/") == 0
		|| die "Fehler beim Schreiben von $file nach " . 
		    "/homes/netz/walther/smbmounts/magnolie/Emacs/site-lisp/op-project/";
    system ("cp", 
	    "/homes/netz/walther/op-project/$file", 
	    "/homes/netz/walther/op-project/installation/") == 0
		|| die "Fehler beim Schreiben von $file nach " . 
		    "/homes/netz/walther/op-project/installation/";
    system ("cp", 
	    "/homes/netz/walther/op-project/$file", 
	    "/usr/local/share/emacs/site-lisp/op-project/") == 0
		|| die "Fehler beim Schreiben von $file nach " . 
		    "/usr/local/share/emacs/site-lisp/op-project/";
}


## zuerste Samba-Mount des NT-Servers!!	 smbmount
##"\\\\magnolie\\programme" -c 'mount
##/homes/netz/walther/smbmounts/magnolie')";

# Kopie der einzelnen Files

# Kopie des Project-Modes
my_copy("op-project.elc");
my_copy("op-indent.elc");

# Kopie des Kalenders
my_copy("op-calendar/op-calendar.elc");
my_copy("op-calendar/op-calendar-holidaylist.elc");





