(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(backup-by-copying t)
 '(bar-cursor nil)
 '(blink-cursor-mode nil)
 '(buffers-menu-format-buffer-line-function (quote slow-format-buffers-menu-line))
 '(column-number-mode t)
 '(complex-buffers-menu-p nil)
 '(delete-old-versions t)
 '(enable-local-variables :safe)
 '(font-lock-maximum-size 500000)
 '(icicle-reminder-prompt-flag 6)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(interprogram-cut-function nil t)
 '(interprogram-paste-function (quote x-cut-buffer-or-selection-value) t)
 '(kept-new-versions 5)
 '(kept-old-versions 5)
 '(kill-whole-line t)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-wheel-scroll-amount (quote (3 ((shift)) ((control) . 10))))
 '(paren-mode (quote sexp-surround) nil (paren))
 '(pc-selection-mode t nil (pc-select))
 '(permanent-buffers-alist nil)
 '(safe-local-variable-values (quote ((Syntax . ANSI-Common-Lisp) (Base . 10) (Syntax . Common-Lisp))))
 '(save-place-file "~/.emacs.d/places.el")
 '(scroll-bar-mode (quote right))
 '(show-paren-mode t)
 '(show-paren-style (quote expression))
 '(show-trailing-whitespace t)
 '(signal-error-on-buffer-boundary nil)
 '(slime-kill-without-query-p t)
 '(slime-repl-history-size 3000)
 '(swbuff-clear-delay 3)
 '(swbuff-clear-delay-ends-switching t)
 '(swbuff-exclude-buffer-regexps (quote ("^ " "\\*.*\\*")))
 '(swbuff-separator " ### ")
 '(tool-bar-mode nil)
 '(toolbar-visible-p nil)
 '(tramp-remote-process-environment (quote ("HISTFILE=$HOME/.tramp_history" "HISTSIZE=1" "LC_ALL=C" "TERM=dumb" "CDPATH=" "HISTORY=" "MAIL=" "MAILCHECK=" "MAILPATH=" "autocorrect=" "correct=" "LANG=en_US.UTF-8")))
 '(transient-mark-mode t)
 '(truncate-lines t)
 '(undo-limit 3000000)
 '(undo-strong-limit 5000000)
 '(unshifted-motion-keys-deselect-region t)
 '(version-control t)
 '(warning-suppress-types (quote ((undo discard-info))))
 '(whitespace-auto-cleanup t)
 '(whitespace-check-indent-whitespace nil)
 '(whitespace-global-mode nil)
 '(whitespace-indent-regexp "lofasztcsereldleaspacettabra")
 '(whitespace-indentation-regexp "youllnevermatchthissucker")
 '(whitespace-modes (quote (ada-mode asm-mode autoconf-mode awk-mode c-mode c++-mode cc-mode change-log-mode cperl-mode electric-nroff-mode emacs-lisp-mode f90-mode fortran-mode html-mode html3-mode java-mode jde-mode ksh-mode latex-mode LaTeX-mode lisp-mode m4-mode makefile-mode modula-2-mode nroff-mode objc-mode pascal-mode perl-mode prolog-mode python-mode scheme-mode sgml-mode sh-mode shell-script-mode simula-mode tcl-mode tex-mode texinfo-mode vrml-mode xml-mode lisp-mode)))
 '(x-select-enable-clipboard t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:stipple nil :background "#ffffff" :foreground "#000000" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 113 :width normal :family "misc-fixed"))) t)
 '(bold ((t (:bold t))))
 '(bold-italic ((t (:bold t :italic t))))
 '(font-lock-builtin-face ((((class color) (background light)) (:foreground "Purple3"))))
 '(font-lock-comment-face ((((class color) (background light)) (:foreground "#88c"))))
 '(font-lock-constant-face ((t (:foreground "CadetBlue" :weight normal))))
 '(font-lock-function-name-face ((((class color) (background light)) (:foreground "brown4" :bold t))))
 '(font-lock-keyword-face ((((class color) (background light)) (:foreground "#a00"))))
 '(font-lock-preprocessor-face ((((class color) (background light)) (:foreground "#00a"))))
 '(font-lock-type-face ((((class color) (background light)) (:foreground "steelblue" :bold t))))
 '(font-lock-warning-face ((t (:foreground "Red3" :weight bold))))
 '(paren-match ((t (:background "#d0ffff"))) t)
 '(show-paren-match ((((class color) (background light)) (:background "#d0ffff"))))
 '(sldb-catch-tag-face ((t (:foreground "yellow4"))))
 '(sldb-condition-face ((t (:bold t))))
 '(sldb-frame-label-face ((t (:foreground "#888"))))
 '(sldb-frame-line-face ((t nil)))
 '(sldb-restart-face ((t (:foreground "darkmagenta" :bold nil))))
 '(sldb-restart-number-face ((t (:foreground "darkmagenta" :bold t))))
 '(sldb-restart-type-face ((t (:foreground "darkmagenta" :bold nil))))
 '(sldb-section-face ((t (:foreground "darkblue" :bold t))))
 '(sldb-topline-face ((t (:foreground "darkred" :bold t))))
 '(slime-error-face ((((class color) (background light)) (:foreground "darkred" :bold t))))
 '(slime-inspector-value-face ((((background light)) (:foreground "MediumBlue" :bold t))))
 '(slime-note-face ((((class color) (background light)) (:background "grey80" :underline t))))
 '(slime-reader-conditional-face ((((background light)) (:foreground "DimGray" :bold t))))
 '(slime-repl-input-face ((t (:bold t))))
 '(slime-repl-output-mouseover-face ((t (:bold t))))
 '(slime-style-warning-face ((((class color) (background light)) (:underline t))))
 '(slime-warning-face ((((class color) (background light)) (:foreground "darkred" :underline t))))
 '(swbuff-current-buffer-face ((t (:foreground "red" :bold t :underline t))))
 '(trailing-whitespace ((((class color) (background light)) (:background "#fff0f0")))))
(put 'narrow-to-region 'disabled nil)
