#!/bin/sh

ARGS=$@

if [ -z $ARGS ]; then
  ARGS="screen -Rd"
fi

CMD="ssh -t -C -Y -L 5000:localhost:5000 -L 15000:localhost:15000 -L 15001:localhost:15001 -L 15002:localhost:5432 -L 8085:localhost:8080 \
 -o ControlPath=none -o ServerAliveInterval=60 tintas@pantoserver $ARGS"

echo Executing $CMD

$CMD
